'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

# The Fibonacci sequence can be described using a mathematical equation: Xn+2 = Xn+1 + Xn
'''
t = pt + ppt
1 = 1 + 0
2 = 1 + 1
3 = 2 + 1
5 = 3 + 2
8 = 5 + 3
13 = 8 + 5
21 = 13 + 8
34 = 21 + 13
55 = 34 + 21 
89 = 55 + 34
'''


t = 0
pt = 1
ppt = 0
sum = 0 

while t < 4000000:
    t = pt + ppt
    ppt = pt
    pt = t

    if t < 4000000:
        if(t % 2 == 0):
            sum = sum + t
            print(sum)
    else: break

